common: &common
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  port: 5548
  username: msandbox
  password: msandbox
  protocol: TCP
  host: 127.0.0.1

development:
  <<: *common
  database: allegro_dev
  pool: 10

test:
  <<: *common
  database: allegro_test 
